	var path = "http://www.ninjastatus.com/last_stop/Brooklyn/"
	var stations = [
	// Brooklyn
	{ loc: "1919,3571,16", name: "Coney Island/ Stillwell Av", line: ["D", "F", "N", "Q"], imgName: [ path + "coney_island_stillwell_avenue_d_f_n_q.jpg" ]},
    { loc: "1957,3551,16", name: "West 8 st/ NY Aquarium", line: ["F", "Q"], imgName: [ path + "west_8_street_new_york_aquarium_f_q.jpg", path + "west_8_street_new_york_aquarium_f_q-2.jpg" ]},
    { loc: "2020,3506,16", name: "Ocean Pkwy", line: ["Q"], imgName: [ path + "ocean_parkway_q.jpg", path + "ocean_parkway_q-2.jpg", path + "ocean_parkway_q-3.jpg" ]},
    { loc: "2043,3470,16", name: "Brighton Beach", line: ["B", "Q"], imgName: [ path + "brighton_beach_b_q.jpg", path + "brighton_beach_b_q-2.jpg", path + "brighton_beach_b_q-3.jpg" ]},
    { loc: "2032,3429,16", name: "Sheepshead Bay", line: ["B", "Q"], imgName: [ path + "sheepshead_bay_b_q.jpg", path + "sheepshead_bay_b_q-2.jpg" ]},
    { loc: "2006,3408,16", name: "Neck Rd", line: ["B, Q"], imgName: [ path + "neck_road_b_q.jpg", path + "neck_road_b_q-2.jpg" ]},
    { loc: "1982,3381,16", name: "Avenue U", line: ["B", "Q"], imgName: [ path + "avenue_u_b_q.jpg" ]},
    { loc: "1938,3332,16", name: "Kings Hwy", line: ["B", "Q"], imgName: [ path + "kings_highway_b_q.jpg", path + "kings_highway_b_q-2.jpg" ]},
    { loc: "1886,3281,16", name: "Avenue M", line: ["B", "Q"], imgName: [ path + "avenue_m_b_q.jpg", path + "avenue_m_b_q-2.jpg" ]},
    { loc: "1847,3242,16", name: "Avenue J", line: ["B", "Q"], imgName: [ path + "avenue_j_b_q.jpg" ]},
    { loc: "1808,3198,18", name: "Avenue H", line: ["B", "Q"], imgName: [ path + "avenue_h_b_q.jpg", path + "avenue_h_b_q-2.jpg", path + "avenue_h_b_q-3.jpg" ]},
    { loc: "1779,3169,16", name: "Newkirk Plaza", line: ["B", "Q"], imgName: [ path + "newkirk_avenue_b_q.jpg", path + "newkirk_avenue_b_q-2.jpg" ]},
    { loc: "1750,3147,14", name: "Cortelyou Rd", line: ["B, Q"], imgName: [ path + "cortelyou_road_b_q.jpg", path + "cortelyou_road_b_q-2.jpg" ]},
    { loc: "1734,3123,14", name: "Beverley Rd", line: ["B", "Q"], imgName: [ path + "beverley_road_b_q.jpg" ]},
    { loc: "1713,3104,14", name: "Church Av", line: ["B", "Q"], imgName: [ path + "church_avenue_b_q.jpg" ]},
    { loc: "1703,3058,16", name: "Parkside Av", line: ["Q"], imgName: [ path + "parkside_avenue_q.jpg" ]},
    { loc: "1966,3501,16", name: "Neptune Av", line: ["F"], imgName: [ path + "neptune_avenue_f.jpg" ]},
    { loc: "1941,3479,16", name: "Avenue X", line: ["F"], imgName: [ path + "avenue_x_f.jpg" ]},
    { loc: "1912,3444,16", name: "Avenue U", line: ["F"], imgName: [ path + "avenue_u_f.jpg", path + "avenue_u_f-2.jpg" ]},
    { loc: "1866,3396,16", name: "Kings Hwy", line: ["F"], imgName: [ path + "kings_highway_f.jpg", path + "kings_highway_f-2.jpg" ]},
    { loc: "1840,3378,16", name: "Avenue P", line: ["F"], imgName: [ path + "avenue_p_f.jpg", path + "avenue_p_f-2.jpg" ]},
    { loc: "1825,3349,16", name: "Avenue N", line: ["F"], imgName: [ path + "avenue_n_f.jpg", path + "avenue_n_f-2.jpg", path + "avenue_n_f-3.jpg" ]},
    { loc: "1773,3302,16", name: "Bay Pkwy", line: ["F"], imgName: [ path + "bay_parkway_f.jpg", path + "bay_parkway_f-2.jpg" ]},
    { loc: "1747,3274,16", name: "Avenue I", line: ["F"], imgName: [ path + "avenue_i_f.jpg", path + "avenue_i_f-2.jpg" ]},
    { loc: "1723,3249,16", name: "18 Av", line: ["F"], imgName: [ path + "18_avenue_f-2.jpg", path + "18_avenue_f-3.jpg", path + "18_avenue_f-4.jpg", path + "18_avenue_f.jpg" ]},
    { loc: "1699,3227,16", name: "Ditmas Av", line: ["F"], imgName: [ path + "ditmas_avenue_f.jpg", path + "ditmas_avenue_f-2.jpg", path + "ditmas_avenue_f-3.jpg" ]},
    { loc: "1656,3177,16", name: "Church Av", line: ["F", "G"], imgName: [ path + "church_avenue_f_g.jpg", path + "church_avenue_f_g-2.jpg", path + "church_avenue_f_g-3.jpg", path + "church_avenue_f_g-4.jpg", path + "church_avenue_f_g-5.jpg" ]},
    { loc: "1641,3128,16", name: "Fort Hamilton Pkwy", line: ["F", "G"], imgName: [ path + "fort_hamilton_parkway_f_g.jpg", path + "fort_hamilton_parkway_f_g-2.jpg", path + "fort_hamilton_parkway_f_g-3.jpg", path + "fort_hamilton_parkway_f_g-4.jpg" ]},
    { loc: "1584,3038,16", name: "15 St/ Prospect Park", line: ["F", "G"], imgName: [ path + "15_street_prospect_park_f_g-2.jpg", path + "15_street_prospect_park_f_g-3.jpg", path + "15_street_prospect_park_f_g-4.jpg", path + "15_street_prospect_park_f_g-5.jpg", path + "15_street_prospect_park_f_g-6.jpg", path + "15_street_prospect_park_f_g.jpg"]},
    { loc: "1873,3528,16", name: "Bay 50 St", line: ["D"], imgName: [ path + "bay_50_street_d.jpg", path + "bay_50_street_d-2.jpg" ]},
    { loc: "1836,3499,16", name: "25 Av", line: ["D"], imgName: [ path + "25_avenue_d.jpg", path + "25_avenue_d-2.jpg" ]},
    { loc: "1774,3494,16", name: "Bay Pkwy", line: ["D"], imgName: [ path + "bay_parkway_d.jpg" ]},
    { loc: "1744,3490,14", name: "20 Av", line: ["D"], imgName: [ path + "20_avenue_d-2.jpg", path + "20_avenue_d.jpg" ]},
    { loc: "1714,3482,16", name: "18 Av", line: ["D"], imgName: [ path + "18_avenue_d-2.jpg", path + "18_avenue_d-3.jpg", path + "18_avenue_d.jpg"]},
    { loc: "1692,3455,16", name: "79 St", line: ["D"], imgName: [ path + "79_street_d.jpg", path + "79_street_d-2.jpg" ]},
    { loc: "1671,3418,16", name: "71 St", line: ["D"], imgName: [ path + "71_street_d.jpg", path + "71_street_d-2.jpg" ]},
    { loc: "1646,3371,16", name: "62 St", line: ["D"], imgName: [ path + "62_street_d.jpg", path + "62_street_d-2.jpg" ]},
    { loc: "1906,3493,16", name: "86 St", line: ["N"], imgName: [ path + "86_street_n.jpg" ]},
    { loc: "1882,3472,16", name: "Avenue U", line: ["N"], imgName: [ path + "avenue_u_n.jpg" ]},
    { loc: "1821,3413,16", name: "Kings Hwy", line: ["N"], imgName: [ path + "kings_highway_n.jpg" ]},
    { loc: "1787,3381,16", name: "Bay Pkwy", line: ["N"], imgName: [ path + "bay_parkway_n.jpg" ]},
    { loc: "1751,3368,16", name: "20 Av", line: ["N"], imgName: [ path + "20_avenue_n.jpg" ]},
    { loc: "1717,3362,16", name: "18 Av", line: ["N"], imgName: [ path + "18_avenue_n.jpg" ]},
    { loc: "1603,3365,16", name: "New Utrecht Av", line: ["N", "D"], imgName: [ path + "new_utrecht_avenue_n_d.jpg", path + "new_utrecht_avenue_n_d-2.jpg" ]},
    { loc: "1550,3362,16", name: "Fort Hamilton Pkwy", line: ["N"], imgName: [ path + "fort_hamilton_parkway_n.jpg" ]},
    { loc: "1492,3363,16", name: "8 Av", line: ["N"], imgName: [ path + "8_avenue_n.jpg" ]},
    { loc: "1612,3316,16", name: "55 St", line: ["D"], imgName: [ path + "55_street_d.jpg", path + "55_street_d-2.jpg" ]},
    { loc: "1591,3289,16", name: "50 St", line: ["D"], imgName: [ path + "50_street_d.jpg", path + "50_street_d-2.jpg" ]},
    { loc: "1566,3257,16", name: "Fort Hamilton Pkwy", line: ["D"], imgName: [ path + "fort_hamilton_parkway_d.jpg", path + "fort_hamilton_parkway_d-2.jpg" ]},
    { loc: "1535,3236,16", name: "9 Av", line: ["D"], imgName: [ path + "9_avenue_d.jpg", path + "9_avenue_d-2.jpg" ]},
    { loc: "1675,2982,16", name: "Prospect Park", line: ["B", "Q", "S"], imgName: [ path + "prospect_park_b_q_s.jpg", path + "prospect_park_b_q_s-2.jpg" ]},
    { loc: "1904,3104,16", name: "Flatbush Av/ Brooklyn College", line: ["2", "5"], imgName: [ path + "flatbush_avenue_2_5.jpg", path + "flatbush_avenue_2_5-2.jpg", path + "flatbush_avenue_2_5-3.jpg" ]},
    { loc: "1860,3057,16", name: "Newkirk Av", line: ["2", "5"], imgName: [ path + "newkirk_avenue_2_5.jpg" ]},
    { loc: "1837,3035,16", name: "Beverly Rd", line: ["2", "5"], imgName: [ path + "beverley_road_2_5.jpg" ]},
    { loc: "1817,3008,16", name: "Church Av", line: ["2", "5"], imgName: [ path + "church_avenue_2_5.jpg", path + "church_avenue_2_5-2.jpg", path + "church_avenue_2_5-3.jpg" ]},
    { loc: "1783,2979,16", name: "Winthrop St", line: ["2", "5"], imgName: [ path + "winthrop_street_2_5.jpg", path + "winthrop_street_2_5-2.jpg" ]},
    { loc: "1751,2940,16", name: "Sterling St", line: ["2", "5"], imgName: [ path + "sterling_street_2_5.jpg", path + "sterling_street_2_5-2.jpg" ]},
    { loc: "1724,2920,16", name: "President St", line: ["2", "5"], imgName: [ path + "president_street_2_5.jpg", path + "president_street_2_5-2.jpg" ]},
    { loc: "1744,2876,16", name: "Nostrand Av", line: ["3", "4"], imgName: [ path + "nostrand_avenue_3_4.jpg", path + "nostrand_avenue_3_4-2.jpg" ]},
    { loc: "1813,2838,16", name: "Kingston Av", line: ["3", "4"], imgName: [ path + "kingston_avenue_3_4.jpg" ]},
    { loc: "1875,2793,16", name: "Crown Hts/ Utica Av", line: ["3", "4"], imgName: [ path + "utica_avenue_3_4.jpg", path + "utica_avenue_3_4-2.jpg", path + "utica_avenue_3_4-3.jpg" ]},
    { loc: "1935,2771,16", name: "Sutter Av-Rutland Rd", line: ["3"], imgName: [ path + "sutter_avenue_rutland_road_3.jpg" ]},
    { loc: "1994,2748,16", name: "Saratoga Av", line: ["3"], imgName: [ path + "saratoga_avenue_3.jpg", path + "saratoga_avenue_3-2.jpg" ]},
    { loc: "2036,2709,16", name: "Rockaway Av", line: ["3"], imgName: [ path + "rockaway_avenue_3.jpg" ]},
    { loc: "2067,2681,16", name: "Junius St", line: ["3"], imgName: [ path + "junius_street_3.jpg" ]},
    { loc: "2101,2676,16", name: "Livonia Av", line: ["L"], imgName: [ path + "livonia_avenue_l.jpg", path + "livonia_avenue_l-2.jpg", path + "livonia_avenue_l-3.jpg" ]},
    { loc: "2126,2709,16", name: "New Lots Av", line: ["L"], imgName: [ path + "new_lots_avenue_l.jpg" ]},
    { loc: "2151,2754,16", name: "East 105 St", line: ["L"], imgName: [ path + "east_105_street_l.jpg", path + "east_105_street_l-2.jpg", path + "east_105_street_l-3.jpg" ]},
    { loc: "2164,2826,16", name: "Canarsie/ Rockaway Pkwy", line: ["L"], imgName: [ path + "rockaway_parkway_l.jpg", path + "rockaway_parkway_l-2.jpg" ]},
    { loc: "1473,3517,16", name: "Bay Ridge/ 95 St", line: ["R"], imgName: [ path + "95_street_r.jpg" ]},
    { loc: "1464,3481,16", name: "86 St", line: ["R"], imgName: [ path + "86_street_r.jpg" ]},
    { loc: "1437,3441,18", name: "77 St", line: ["R"], imgName: [ path + "77_street_r.jpg", path + "77_street_r-2.jpg" ]},
    { loc: "1430,3394,16", name: "Bay Ridge Av", line: ["R"], imgName: [ path + "bay_ridge_avenue_r.jpg", path + "bay_ridge_avenue_r-2.jpg" ]},
    { loc: "1436,3333,16", name: "59 St", line: ["N", "R"], imgName: [ path + "59_street_n_r.jpg", path + "59_street_n_r-2.jpg" ]},
    { loc: "1441,3292,16", name: "53 St", line: ["R"], imgName: [ path + "53_street_r.jpg", path + "53_street_r-2.jpg" ]},
    { loc: "1438,3247,16", name: "45 St", line: ["R"], imgName: [ path + "45_street_r.jpg", path + "45_street_r-2.jpg" ]},
    { loc: "1451,3204,16", name: "36 St", line: ["D", "N", "R"], imgName: [ path + "36_street_d_n_r.jpg" ]},
    { loc: "1437,3126,16", name: "25 St", line: ["R"], imgName: [ path + "25_street_r.jpg" ]},
    { loc: "1439,3072,16", name: "Prospect Av", line: ["R"], imgName: [ path + "prospect_avenue_r.jpg" ]},
    { loc: "1534,3011,16", name: "7 Av", line: ["F", "G"], imgName: [ path + "7_avenue_f_g.jpg", path + "7_avenue_f_g-2.jpg", path + "7_avenue_f_g-3.jpg" ]},
    { loc: "1443,2994,16", name: "4 Av-9 St", line: ["R"], imgName: [ path + "9_street_r.jpg" ]},
    { loc: "1412,3003,16", name: "4 Av", line: ["F", "G", "R"], imgName: [ path + "4_avenue_9_street_f_g_r.jpg" ]},
    { loc: "1377,3003,16", name: "Smith/ 9 Sts", line: ["F", "G"], imgName: [ path + "smith_9_streets_f_g.jpg" ]},
    { loc: "1344,2970,17", name: "Carroll St", line: ["F", "G"], imgName: [ path + "carroll_street_f_g.jpg", path + "carroll_street_f_g-2.jpg" ]},
    { loc: "1340,2934,16", name: "Bergen St", line: ["F", "G"], imgName: [ path + "bergen_street_f_g.jpg", path + "bergen_street_f_g-2.jpg", path + "bergen_street_f_g-3.jpg", path + "bergen_street_f_g-4.jpg" ]},
    { loc: "1439,2952,16", name: "Union St", line: ["R"], imgName: [ path + "union_street_r.jpg", path + "union_street_r-2.jpg" ]},
    { loc: "1443,2899,16", name: "Atlantic Av-Pacific St", line: ["D", "N", "R"], imgName: [ path + "atlantic_avenue_pacific_street_d_n_r.jpg" ]},
    { loc: "1483,2879,16", name: "Atlantic Av", line: ["2", "3", "4", "5", "B", "Q", "N", "R", "D"], imgName: [ path + "atlantic_avenue_barclays_center_2_3_4_5_b_q_n_r_d.jpg", path + "atlantic_avenue_b_q_2_3_4_5-2.jpg", path + "atlantic_avenue_b_q_2_3_4_5_n_r_d.jpg" ]},
    { loc: "1527,2913,16", name: "Bergen St", line: ["2", "3"], imgName: [ path + "bergen_street_2_3.jpg", path + "bergen_street_2_3-2.jpg", path + "bergen_street_2_3-3.jpg" ]},
    { loc: "1559,2898,16", name: "7 Av", line: ["B", "Q"], imgName: [ path + "7_avenue_b_q.jpg", path + "7_avenue_b_q-2.jpg" ]},
    { loc: "1569,2932,16", name: "Grand Army Plaza", line: ["2", "3"], imgName: [ path + "grand_army_plaza_2_3.jpg", path + "grand_army_plaza_2_3-2.jpg" ]},
    { loc: "1636,2928,16", name: "Eastern Pkwy/ Brooklyn Museum", line: ["2", "3"], imgName: [ path + "eastern_parkway_brooklyn_museum_2_3.jpg", path + "eastern_parkway_brooklyn_museum_2_3-2.jpg", path + "eastern_parkway_brooklyn_museum_2_3-3.jpg" ]},
    { loc: "1671,2935,16", name: "Botanic Garden", line: ["S", "2", "3", "4", "5"], imgName: [ path + "botanic_garden_s_2_3_4_5.jpg" ]},
    { loc: "1680,2902,16", name: "Franklin Av", line: ["S", "2", "3", "4", "5"], imgName: [ path + "franklin_avenue_2_3_4_5_s.jpg", path + "franklin_avenue_2_3_4_5_s-2.jpg", path + "franklin_avenue_2_3_4_5_s-3.jpg", path + "franklin_avenue_2_3_4_5_s-4.jpg" ]},
    { loc: "1651,2873,16", name: "Park Pl", line: ["S"], imgName: [ path + "park_place_s.jpg" ]},
    { loc: "1387,2885,16", name: "Hoyt Schermerhorn", line: ["A", "C", "G"], imgName: [ path + "hoyt_schermerhorn_streets_a_c_g.jpg", path + "hoyt_schermerhorn_streets_a_c_g-2.jpg" ]},
    { loc: "1423,2852,16", name: "Nevins St", line: ["2", "3", "4", "5"], imgName: [ path + "nevins_street_2_3_4_5.jpg", path + "nevins_street_2_3_4_5-2.jpg", path + "nevins_street_2_3_4_5-3.jpg" ]},
    { loc: "1371,2846,16", name: "Hoyt St", line: ["2", "3"], imgName: [ path + "hoyt_street_2_3.jpg", path + "hoyt_street_2_3-2.jpg" ]},
    { loc: "1489,2836,16", name: "Lafayette Av", line: ["A", "C"], imgName: [ path + "lafayette_avenue_a_c.jpg", path + "lafayette_avenue_a_c-2.jpg", path + "lafayette_avenue_a_c-3.jpg", path + "lafayette_avenue_a_c-4.jpg" ]},
    { loc: "1544,2812,16", name: "Clinton Washington Avs", line: ["A", "C"], imgName: [ path + "clinton_washington_avenues_a_c.jpg", path + "clinton_washington_avenues_a_c-2.jpg" ]},
    { loc: "1630,2777,16", name: "Franklin Av", line: ["A", "C", "S"], imgName: [ path + "franklin_avenue_a_c_s.jpg", path + "franklin_avenue_a_c_s-2.jpg", path + "franklin_avenue_a_c_s-3.jpg" ]},
    { loc: "1679,2754,16", name: "Nostrand Av", line: ["A", "C"], imgName: [ path + "nostrand_avenue_a_c.jpg", path + "nostrand_avenue_a_c-2.jpg" ]},
    { loc: "1713,2718,16", name: "Kingston/ Throop Avs", line: ["A", "C"], imgName: [ path + "kingston_throop_avenues_a_c.jpg", path + "kingston_throop_avenues_a_c-2.jpg" ]},
    { loc: "1322,2850,16", name: "Borough Hall", line: ["2", "3", "4", "5"], imgName: [ path + "bourough_hall_2_3_4_5.jpg", path + "bourough_hall_2_3_4_5-2.jpg" ]},
    { loc: "1290,2848,16", name: "Court St", line: ["R"], imgName: [ path + "court_street_r.jpg" ]},
    { loc: "1318,2817,16", name: "Jay St/ MetroTech", line: ["A", "C", "F", "R"], imgName: [ path + "jay_street_metro_tech_a_c_f_r.jpg", path + "jay_street_metro_tech_a_c_f_r-2.jpg", path + "jay_street_metro_tech_a_c_f_r-3.jpg", path + "jay_street_metro_tech_a_c_f_r-4.jpg" ]},
    { loc: "1220,2834,16", name: "Clark St", line: ["2", "3"], imgName: [ path + "clark_street_2_3.jpg" ]},
    { loc: "1234,2767,16", name: "High St", line: ["A", "C"], imgName: [ path + "high_street_brooklyn_bridge_a_c.jpg", path + "high_street_brooklyn_bridge_a_c-2.jpg" ]},
    { loc: "1418,2813,16", name: "Dekalb Av", line: ["B", "Q", "R"], imgName: [ path + "dekalb_avenue_b_q_r.jpg", path + "dekalb_avenue_b_q_r-2.jpg", path + "dekalb_avenue_b_q_r-3.jpg" ]},
    { loc: "1467,2812,16", name: "Fulton St", line: ["G"], imgName: [ path + "fulton_street_g.jpg", path + "fulton_street_g-2.jpg", path + "fulton_street_g-3.jpg" ]},
    { loc: "1282,2711,16", name: "York St", line: ["F"], imgName: [ path + "york_street_f.jpg" ]},
    { loc: "1514,2788,16", name: "Clinton Washington Avs", line: ["G"], imgName: [ path + "clinton_washington_avenues_g.jpg", path + "clinton_washington_avenues_g-2.jpg", path + "clinton_washington_avenues_g-3.jpg", path + "clinton_washington_avenues_g-4.jpg" ]},
    { loc: "1546,2749,16", name: "Classon Av", line: ["G"], imgName: [ path + "classon_avenue_g.jpg", path + "classon_avenue_g-2.jpg" ]},
    { loc: "1587,2712,16", name: "Bedford Nostrand Avs", line: ["G"], imgName: [ path + "bedford_nostrand_avenues_g.jpg", path + "bedford_nostrand_avenues_g-2.jpg", path + "bedford_nostrand_avenues_g-3.jpg" ]},
    { loc: "1549,2643,16", name: "Myrtle Willoughby Avs", line: ["G"], imgName: [ path + "myrtle_willoughby_avenues_g.jpg", path + "myrtle_willoughby_avenues_g-2.jpg" ]},
    { loc: "1496,2595,16", name: "Flushing Av", line: ["G"], imgName: [ path + "flushing_avenue_g.jpg", path + "flushing_avenue_g-2.jpg" ]},
    { loc: "1353,2575,16", name: "Marcy Av", line: ["J", "M", "Z"], imgName: [ path + "marcy_avenue_j_m_z.jpg", path + "marcy_avenue_j_m_z-2.jpg" ]},
    { loc: "1420,2568,16", name: "Hewes St", line: ["J", "M"], imgName: [ path + "hewes_street_j_m.jpg" ]},
    { loc: "1449,2553,16", name: "Broadway", line: ["G"], imgName: [ path + "broadway_g.jpg", path + "broadway_g-2.jpg" ]},
    { loc: "1481,2558,16", name: "Lorimer St", line: ["J", "M"], imgName: [ path + "lorimer_street_j_m.jpg", path + "lorimer_street_j_m-2.jpg", path + "lorimer_street_j_m-3.jpg" ]},
    { loc: "1519,2558,16", name: "Flushing Av", line: ["J", "M"], imgName: [ path + "flushing_avenue_j_m.jpg", path + "flushing_avenue_j_m-2.jpg" ]},
    { loc: "1627,2556,16", name: "Myrtle Av", line: ["J", "M", "Z"], imgName: [ path + "myrtle_avenue_j_m_z.jpg", path + "myrtle_avenue_j_m_z-2.jpg" ]},
    { loc: "1708,2556,16", name: "Kosciuszko St", line: ["J"], imgName: [ path + "kosciuszko_street_j.jpg", path + "kosciuszko_street_j-2.jpg" ]},
    { loc: "1778,2550,16", name: "Gates Av", line: ["J", "Z"], imgName: [ path + "gates_avenue_j_z.jpg", path + "gates_avenue_j_z-2.jpg" ]},
    { loc: "1824,2546,16", name: "Halsey St", line: ["J"], imgName: [ path + "halsey_street_j.jpg" ]},
    { loc: "1868,2545,16", name: "Chauncey St", line: ["J", "Z"], imgName: [ path + "chauncey_street_j_z.jpg", path + "chauncey_street_j_z-2.jpg" ]},
    { loc: "1951,2542,16", name: "Broadway Junction", line: ["L", "C", "A", "J", "M"], imgName: [ path + "broadway_junction_a_c_l_j_m.jpg", path + "broadway_junction_a_c_l_j_m-2.jpg" ]},
    { loc: "1991,2523,16", name: "Alabama Av", line: ["J"], imgName: [ path + "alabama_avenue_j.jpg", path + "alabama_avenue_j-2.jpg" ]},
    { loc: "2032,2494,16", name: "Van Siclen Av", line: ["J", "Z"], imgName: [ path + "van_siclen_avenue_j_z.jpg", path + "van_siclen_avenue_j_z-2.jpg", path + "van_siclen_avenue_j_z-3.jpg" ]},
    { loc: "2062,2472,16", name: "Cleveland St", line: ["J"], imgName: [ path + "cleveland_street_j.jpg", path + "cleveland_street_j-2.jpg" ]},
    { loc: "2083,2442,16", name: "Norwood Av", line: ["J", "Z"], imgName: [ path + "norwood_avenue_j_z.jpg", path + "norwood_avenue_j_z-2.jpg" ]},
    { loc: "2088,2408,16", name: "Crescent St", line: ["J", "Z"], imgName: [ path + "crescent_street_j_z.jpg" ]},
    { loc: "2074,2372,16", name: "Cypress Hills", line: ["J", "Z"], imgName: [ path + "cypress_hills_j.jpg", path + "cypress_hills_j_z-2.jpg" ]},
    { loc: "2205,2448,16", name: "Grant Av", line: ["A", "C"], imgName: [ path + "grant_avenue_a_c.jpg" ]},
    { loc: "2174,2484,16", name: "Euclid Av", line: ["A", "C"], imgName: [ path + "euclid_avenue_a_c.jpg", path + "euclid_avenue_a_c-2.jpg", path + "euclid_avenue_a_c-3.jpg" ]},
    { loc: "2140,2524,16", name: "Shepherd Av", line: ["A", "C"], imgName: [ path + "shepherd_avenue_a_c.jpg", path + "shepherd_avenue_a_c-2.jpg" ]},
    { loc: "2089,2549,16", name: "Van Siclen Av", line: ["A", "C"], imgName: [ path + "van_siclen_avenue_a_c.jpg", path + "van_siclen_avenue_a_c-2.jpg" ]},
    { loc: "2050,2548,16", name: "Liberty Av", line: ["A", "C"], imgName: [ path + "liberty_avenue_a_c.jpg", path + "liberty_avenue_a_c-2.jpg", path + "liberty_avenue_a_c-3.jpg" ]},
    { loc: "2052,2635,16", name: "Sutter Av", line: ["L"], imgName: [ path + "sutter_avenue_l.jpg" ]},
    { loc: "1984,2579,16", name: "Atlantic Av", line: ["L"], imgName: [ path + "atlantic_avenue_l.jpg", path + "atlantic_avenue_l-2.jpg", path + "atlantic_avenue_l-3.jpg" ]},
    { loc: "2116,2646,16", name: "Pennsylvania Av", line: ["3"], imgName: [ path + "pennsylvania_avenue_3.jpg", path + "pennsylvania_avenue_3-2.jpg" ]},
    { loc: "2137,2622,16", name: "Van Siclen Av", line: ["3"], imgName: [ path + "van_siclen_3.jpg" ]},
    { loc: "2162,2597,16", name: "New Lots Av", line: ["3"], imgName: [ path + "new_lots_avenue_3.jpg" ]},
    { loc: "1891,2589,16", name: "Rockaway Av", line: ["A", "C"], imgName: [ path + "rockaway_avenue_a_c.jpg", path + "rockaway_avenue_a_c-2.jpg", path + "rockaway_avenue_a_c-3.jpg" ]},
    { loc: "1846,2626,16", name: "Ralph Av", line: ["A", "C"], imgName: [ path + "ralph_avenue_a_c.jpg", path + "ralph_avenue_a_c-2.jpg" ]},
    { loc: "1788,2662,16", name: "Utica Av", line: ["A", "C"], imgName: [ path + "utica_avenue_a_c.jpg", path + "utica_avenue_a_c-2.jpg" ]},
    { loc: "1909,2519,16", name: "Bushwick Av/ Aberdeen St", line: ["L"], imgName: [ path + "bushwick_avenue_aberdeen_street_l.jpg", path + "bushwick_avenue_aberdeen_street_l-2.jpg" ]},
    { loc: "1865,2479,16", name: "Wilson Av", line: ["L"], imgName: [ path + "wilson_avenue_l.jpg", path + "wilson_avenue_l-2.jpg" ]},
    { loc: "1824,2448,16", name: "Halsey St", line: ["L"], imgName: [ path + "halsey_street_l.jpg", path + "halsey_street_l-2.jpg", path + "halsey_street_l-3.jpg" ]},
    { loc: "1752,2436,16", name: "Myrtle Wyckoff Avs", line: ["L", "M"], imgName: [ path + "myrtle_wyckoff_avenue_l_m.jpg", path + "myrtle_wyckoff_avenue_l_m-2.jpg", path + "myrtle_wyckoff_avenue_l_m-3.jpg" ]},
    { loc: "1727,2475,16", name: "Knickerbocker Av", line: ["M"], imgName: [ path + "knickerbocker_avenue_m.jpg" ]},
    { loc: "1692,2502,16", name: "Central Av", line: ["M"], imgName: [ path + "central_avenue_m.jpg", path + "central_avenue_m-2.jpg" ]},
    { loc: "1686,2434,16", name: "DeKalb Av", line: ["L"], imgName: [ path + "dekalb_avenue_l.jpg", path + "dekalb_avenue_l-2.jpg" ]},
    { loc: "1633,2434,16", name: "Jefferson St", line: ["L"], imgName: [ path + "jefferson_street_l.jpg", path + "jefferson_street_l-2.jpg", path + "jefferson_street_l-3.jpg" ]},
    { loc: "1553,2476,16", name: "Morgan Av", line: ["L"], imgName: [ path + "morgan_avenue_l.jpg", path + "morgan_avenue_l-2.jpg", path + "morgan_avenue_l-3.jpg" ]},
    { loc: "1515,2473,16", name: "Montrose Av", line: ["L"], imgName: [ path + "montrose_avenue_l.jpg" ]},
    { loc: "1469,2455,16", name: "Grand St", line: ["L"], imgName: [ path + "grand_street_l.jpg", path + "grand_street_l-2.jpg" ]},
    { loc: "1424,2443,16", name: "Graham Av", line: ["L"], imgName: [ path + "graham_avenue_l.jpg" ]},
    { loc: "1363,2490,16", name: "Metropolitan Av", line: ["G", "L"], imgName: [ path + "metropolitan_avenue_g_l.jpg" ]},
    { loc: "1355,2458,16", name: "Lorimer St", line: ["L", "G"], imgName: [ path + "lorimer_street_l_g.jpg" ]},
    { loc: "1248,2457,16", name: "Bedford Av", line: ["L"], imgName: [ path + "bedford_avenue_l.jpg", path + "bedford_avenue_l-2.jpg" ]},
    { loc: "1295,2432,16", name: "Nassau Av", line: ["G"], imgName: [ path + "nassau_avenue_g.jpg", path + "nassau_avenue_g-2.jpg", path + "nassau_avenue_g-3.jpg", path + "nassau_avenue_g-4.jpg" ]},
    { loc: "1248,2397,16", name: "Greenpoint Av", line: ["G"], imgName: [ path + "greenpoint_avenue_g.jpg", path + "greenpoint_avenue_g-2.jpg", path + "greenpoint_avenue_g-3.jpg", path + "greenpoint_avenue_g-4.jpg", path + "greenpoint_avenue_g-5.jpg" ]}
];
